name: universal_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  jaguar: ^2.4.1
  jaguar_dev_proxy:
  data:
    path: ../data
  tuple:
  libpg:
    path: ../../dart/libpg

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
